import React, { useMemo, useRef, useState } from "react";
import { studioEdges, studioNodes, workflows } from "./data";
import { Icon, StatusPill } from "./ui";

const steps = [
  ["repository","Repository","Connected and ready","complete","CircleCheckBig"],
  ["build","Build","Durable draft active","active","CircleDot"],
  ["review","Review","No proposal yet","idle","GitPullRequest"],
  ["preview","Preview","Preview proven","complete","CircleCheckBig"],
  ["production","Production","Not promoted","idle","Rocket"]
];

function Lifecycle({ active, onChange }) {
  return <nav className="lifecycle"><div>{steps.map(([id,label,detail,tone,icon],index) => <React.Fragment key={id}>{index>0&&<i/>}<button className={`${tone} ${active===id?'selected':''}`} onClick={()=>onChange(id)}><span><Icon name={icon} size={14}/></span><b><strong>{label}</strong><small>{detail}</small></b></button></React.Fragment>)}</div></nav>;
}

function WorkflowList({ selected, onSelect }) {
  const [query,setQuery]=useState("");
  const filtered=workflows.filter((item)=>`${item.name} ${item.id}`.toLowerCase().includes(query.toLowerCase()));
  return <aside className="workflow-pane"><div className="repo-card"><div className="repo-head"><div><strong>ahamdjin/Flowcordia</strong><small><Icon name="GitBranch" size={11}/>main · <code>af674704</code></small></div><span className="status-pill success">IDLE</span></div><div className="repo-stats"><span><small>Workflows</small><strong>5</strong></span><span><small>Valid</small><strong>5</strong></span><span><small>Invalid</small><strong>0</strong></span></div><button><Icon name="RefreshCw" size={13}/>Synchronize repository</button></div><label className="workflow-search"><Icon name="Search" size={14}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Filter workflows"/></label><div className="workflow-list">{filtered.map((item)=><button className={selected===item.id?'selected':''} key={item.id} onClick={()=>onSelect(item.id)}><span><strong>{item.name}</strong><i className="status-pill success">Valid</i></span><code>{item.id}</code><small><b>{item.nodes} nodes</b><b>{item.edges} edges</b><code>{item.sha}</code></small></button>)}</div></aside>;
}

function Canvas({ selected, onSelect, names }) {
  const viewport=useRef(null);
  const [zoom,setZoom]=useState(.72);
  const [pan,setPan]=useState({x:-10,y:30});
  const [positions,setPositions]=useState(()=>Object.fromEntries(studioNodes.map((n)=>[n.id,{x:n.x,y:n.y}])));
  const [drag,setDrag]=useState(null);
  const [panning,setPanning]=useState(null);
  const map=useMemo(()=>new Map(studioNodes.map((n)=>[n.id,{...n,...positions[n.id]}])),[positions]);
  const fit=()=>{const box=viewport.current?.getBoundingClientRect();if(!box)return;setZoom(Math.max(.38,Math.min(.82,(box.width-100)/1750,(box.height-90)/650)));setPan({x:40,y:40});};
  const nodeDown=(e,n)=>{e.stopPropagation();onSelect(n.id);setDrag({id:n.id,p:e.pointerId,sx:e.clientX,sy:e.clientY,...positions[n.id]});e.currentTarget.setPointerCapture(e.pointerId);};
  const nodeMove=(e)=>{if(!drag||drag.p!==e.pointerId)return;setPositions((current)=>({...current,[drag.id]:{x:Math.round((drag.x+(e.clientX-drag.sx)/zoom)/20)*20,y:Math.round((drag.y+(e.clientY-drag.sy)/zoom)/20)*20}}));};
  const nodeUp=(e)=>{if(drag?.p===e.pointerId)setDrag(null);};
  const panDown=(e)=>{if(e.target.closest('.canvas-node,.canvas-controls,.minimap'))return;setPanning({p:e.pointerId,sx:e.clientX,sy:e.clientY,...pan});e.currentTarget.setPointerCapture(e.pointerId);};
  const panMove=(e)=>{if(panning?.p===e.pointerId)setPan({x:panning.x+e.clientX-panning.sx,y:panning.y+e.clientY-panning.sy});};
  const panUp=(e)=>{if(panning?.p===e.pointerId)setPanning(null);};
  return <div className={`canvas ${panning?'panning':''}`} ref={viewport} onPointerDown={panDown} onPointerMove={panMove} onPointerUp={panUp} onPointerCancel={panUp} onWheel={(e)=>{e.preventDefault();if(e.ctrlKey||e.metaKey)setZoom((z)=>Math.max(.3,Math.min(1.4,z+(e.deltaY<0?.08:-.08))));else setPan((p)=>({x:p.x-e.deltaX,y:p.y-e.deltaY}));}}><div className="canvas-controls"><button onClick={()=>setZoom((z)=>Math.max(.3,z-.1))}>−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0});}}>{Math.round(zoom*100)}%</button><button onClick={()=>setZoom((z)=>Math.min(1.4,z+.1))}>+</button><i/><button onClick={fit}>Fit</button></div><div className="canvas-world" style={{transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${zoom})`}}><svg width="1850" height="720"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z"/></marker></defs>{studioEdges.map(([a,b,condition])=>{const s=map.get(a),t=map.get(b),x1=s.x+232,y1=s.y+55,x2=t.x,y2=t.y+55,c=Math.max(70,Math.abs(x2-x1)/2);return <g key={`${a}-${b}`}><path d={`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`} markerEnd="url(#arrow)"/>{condition&&<text x={(x1+x2)/2} y={(y1+y2)/2-9}>{condition}</text>}</g>;})}</svg>{studioNodes.map((n)=>{const p=positions[n.id];return <article key={n.id} className={`canvas-node ${n.tone} ${selected===n.id?'selected':''}`} style={{left:p.x,top:p.y}} onPointerDown={(e)=>nodeDown(e,n)} onPointerMove={nodeMove} onPointerUp={nodeUp} onPointerCancel={nodeUp}><i className="target"/><span className="node-meta"><b>{n.kind}</b><code>{n.id}</code></span><strong>{names[n.id]||n.name}</strong><code>{n.operation}</code><small><span>{n.settings} settings</span><span>{n.credentials} credentials</span></small><i className="source">→</i></article>;})}</div><button className="minimap" onClick={fit}>{studioNodes.map((n)=>{const p=positions[n.id];return <i key={n.id} className={`${n.tone} ${selected===n.id?'selected':''}`} style={{left:p.x/10.5,top:p.y/8.2}}/>;})}<span/></button></div>;
}

function Inspector({ selected, names, onRename }) {
  const node=studioNodes.find((n)=>n.id===selected)||studioNodes[0];
  const [tab,setTab]=useState('node');
  const [name,setName]=useState(names[node.id]||node.name);
  React.useEffect(()=>setName(names[node.id]||node.name),[node.id,names]);
  return <aside className="inspector"><section className="workflow-details"><span>Workflow details</span><label>Name<input defaultValue="Customer onboarding"/></label><label>Description<textarea defaultValue="Validates a customer, enriches the account, requests approval when needed, and provisions the workspace."/></label><label>Labels<input defaultValue="onboarding, customer, production"/></label><button>Save workflow details</button></section><nav><button className={tab==='node'?'active':''} onClick={()=>setTab('node')}>Node</button><button className={tab==='runtime'?'active':''} onClick={()=>setTab('runtime')}>Runtime</button><button className={tab==='edges'?'active':''} onClick={()=>setTab('edges')}>Edges</button></nav><section className="inspector-body"><span className="eyebrow">{node.kind}</span><h3>{names[node.id]||node.name}</h3><code>{node.id}</code><i className="ownership"><Icon name="ShieldCheck" size={12}/>Visual editor owned</i>{tab==='node'&&<><label>Display name<input value={name} onChange={(e)=>setName(e.target.value)}/></label><button onClick={()=>onRename(node.id,name)}>Rename node</button><dl><dt>Operation</dt><dd><code>{node.operation}</code></dd><dt>Configuration keys</dt><dd>{node.kind==='approval'?'prompt, timeout, reminder, escalation':node.kind==='trigger'?'idempotency, key TTL, queue TTL':'input, output, timeout'}</dd><dt>Credential references</dt><dd>{node.credentials?'crm_api':'None'}</dd></dl></>}{tab==='runtime'&&<div className="runtime"><label>Queue<select defaultValue="flowcordia-critical"><option>default</option><option>flowcordia-critical</option><option>ai-sessions</option></select></label><label>Machine<select defaultValue="small-1x"><option>micro</option><option>small-1x</option><option>small-2x</option></select></label><label>Maximum duration<input defaultValue="300 seconds"/></label><label>Retry attempts<input defaultValue="3"/></label><button>Save runtime policy</button></div>}{tab==='edges'&&<div className="edge-list">{studioEdges.filter(([a,b])=>a===node.id||b===node.id).map(([a,b,c])=><button key={`${a}-${b}`}><code>{a} → {b}</code>{c&&<span>{c}</span>}<Icon name="ChevronRight" size={13}/></button>)}</div>}</section></aside>;
}

function Operations({ active }) {
  const info={repository:["Repository readiness","Exact production branch identity is healthy.","CircleCheckBig","success"],build:["Test workflow","Structural preview is side-effect free.","FlaskConical","info"],review:["Governed Git review","Publish the durable draft to create a reviewable proposal.","GitPullRequest","neutral"],preview:["Preview deployment","Exact workflow closure is installed.","CircleCheckBig","success"],production:["Production proof","Promotion waits for exact merged and deployed identities.","Rocket","warning"]}[active];
  return <aside className="operations"><header><div><small>Workflow operations</small><strong>{active[0].toUpperCase()+active.slice(1)}</strong></div><span className="status-pill">{info[1].split('.')[0]}</span></header><div className="operations-scroll"><section className="operation-card"><div className={`operation-title ${info[3]}`}><i><Icon name={info[2]} size={16}/></i><span><strong>{info[0]}</strong><small>{info[1]}</small></span></div>{active==='build'&&<><label>Test payload<textarea defaultValue={'{\n  "customerId": "cus_1042",\n  "plan": "enterprise"\n}'}/></label><div className="operation-buttons"><button className="primary-button">Run structural preview</button><button>Live test</button></div></>}{active==='repository'&&<InfoRows rows={[["Repository","ahamdjin/Flowcordia"],["Branch","main"],["Observed commit","af674704"],["Workflow index","5 valid entries"]]}/>} {active==='review'&&<><p>Generated workflow JSON and task source stay bound to one exact proposal head. GitHub checks own promotion.</p><button className="full">Open proposals</button></>}{active==='preview'&&<><InfoRows rows={[["State",<span className="status-pill success">Ready</span>],["Proposal head","0311fa33"],["Closure","4 / 4 workflows"],["Deployment","v43-preview.2"]]}/><button className="primary-button full">Run preview workflow</button></>}{active==='production'&&<><InfoRows rows={[["Proposal","Not merged"],["Deployment","v42 current"],["Operations",<span className="status-pill warning">Check required</span>]]}/><button className="full" disabled>Promote exact proposal</button></>}</section>{active==='build'&&<section className="operation-card"><div className="operation-title success"><i><Icon name="CircleCheckBig" size={16}/></i><span><strong>Latest preview</strong><small>Completed successfully · trusted proof</small></span></div><div className="run-steps">{[1,2,3,4,5,6,7,8].map((n)=><i key={n} className={n===5?'waiting':'done'}/>)}</div><InfoRows rows={[["Run","run_vt8e42"],["Deployment","42"],["Duration","1.8s"]]}/></section>}{active==='production'&&<section className="operation-card"><div className="operation-title warning"><i><Icon name="Clock3" size={16}/></i><span><strong>Approval inbox</strong><small>1 decision is waiting.</small></span></div><div className="approval"><span><strong>Manager approval</strong><small>Customer onboarding · waiting 12m</small></span><span className="status-pill warning">Reminder due</span></div><div className="operation-buttons"><button className="primary-button">Approve</button><button>Reject</button></div></section>}</div></aside>;
}
function InfoRows({rows}){return <dl className="info-rows">{rows.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl>}

export default function Studio(){
  const [active,setActive]=useState('build');
  const [workflow,setWorkflow]=useState(workflows[0].id);
  const [node,setNode]=useState('trigger');
  const [names,setNames]=useState({});
  const current=workflows.find((item)=>item.id===workflow)||workflows[0];
  return <main className="studio"><Lifecycle active={active} onChange={setActive}/><div className="studio-workspace"><section className="studio-main"><WorkflowList selected={workflow} onSelect={setWorkflow}/><div className="canvas-column"><header className="canvas-header"><div><span><strong>{current.name}</strong><i className="status-pill info">Draft v12</i></span><small><b>{current.nodes} nodes</b><b>{current.edges} edges</b><b>Schema 0.5</b><code>{current.sha}</code></small></div><span><button className="primary-button">Publish proposal</button><button>Discard draft</button></span></header><div className="preview-banner"><span><Icon name="CircleCheckBig" size={14}/><strong>Preview: ready</strong>Exact deployment is ready for structural and live testing.</span><code>0311fa33 · deployment 42 · closure 4/4</code></div><div className="draft-strip"><strong>4 draft changes</strong><span>Nodes +1 / ~2 / -0</span><span>Edges +1 / ~0 / -0</span></div><div className="catalog"><label><span>Node catalog</span><i><Icon name="Search" size={13}/><input placeholder="Search approved capabilities"/></i></label><label><span>Category</span><select><option>All categories</option><option>Triggers</option><option>Actions</option><option>Control</option></select></label><label><span>Capability</span><select><option>HTTP request</option><option>Map data</option><option>Condition</option><option>Human approval</option><option>Subflow</option></select></label><button><Icon name="Plus" size={13}/>Add node</button></div><Canvas selected={node} onSelect={setNode} names={names}/></div><Inspector selected={node} names={names} onRename={(id,name)=>setNames((current)=>({...current,[id]:name}))}/></section><Operations active={active}/></div></main>;
}
